AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Public API full serverless on AWS using IaC

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.12
    Architectures:
      - x86_64
    CodeUri: src/
    Environment:
      Variables:
        ATHENA_DATABASE_NAME: turbo_octo_lamb
        ATHENA_OUTPUT_LOCATION: "s3://turbo-octo-lamb-athena-results-113008552223-us-east-1-an/athena-results/"

Resources:
  PublicApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - OPTIONS
        AllowHeaders:
          - Content-Type
  
  GetInventoryMovementsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-client-inventory-movements
      Handler: client_data.inventory.inventory_handler.lambda_handler
      Policies:
        - AthenaQueryPolicy:
            WorkGroupName: primary
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - "arn:aws:s3:::turbo-octo-lamb-mock-data-113008552223-us-east-1-an"
                - "arn:aws:s3:::turbo-octo-lamb-mock-data-113008552223-us-east-1-an/*"
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource:
                - "arn:aws:s3:::turbo-octo-lamb-athena-results-113008552223-us-east-1-an/*"
        - Statement:
            - Effect: Allow
              Action:
                - glue:GetDatabase
                - glue:GetTable
                - glue:GetPartitions
              Resource:
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/turbo_octo_lamb"
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/turbo_octo_lamb/*"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /client-data/inventory/movements
            Method: GET
            ApiId: !Ref PublicApi
            
  GetSalesDepositsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-client-sales-deposits
      Handler: client_data.sales.sales_handler.lambda_handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /client-data/sales/deposits
            Method: GET
            ApiId: !Ref PublicApi

  GetPurchasesDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-client-purchases-details
      Handler: client_data.purchases.purchases_handler.lambda_handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /client-data/purchases/details
            Method: GET
            ApiId: !Ref PublicApi

Outputs:
  ApiEndpoint:
    Description: "Base URL from HTTP API"
    Value: !Sub "https://${PublicApi}.execute-api.${AWS::Region}.amazonaws.com"